### PR TITLE
Dennis dev

### PR DESCRIPTION
**Pull request by dennismwas**
ui patches and fixes being applied .
the new look is below

Forms naona zinatumwa from backend

Screenshot 2024-04-06 at 23 15 07
Screenshot 2024-04-06 at 23 16 41

### CODE REVIEW

**Comment by bretton7700** [comment]
Yes check django forms and widgets for better understanding of the same

**Review by bretton7700 — CHANGES_REQUESTED** [review]
This looks great.
Check the django version and amend before we merge to avoid failure on elastic bean stalk since i use python 3.11.9 which supports django 5.0.4 not 4.2

**Comment by bretton7700** [comment]
merged brother. I love the new UI

**Comment by dennismwas** [comment]
bado messages na forms

**Pull request merged**
